"""message columns added

Revision ID: 0e74959c8fd2
Revises: d40254589bb1
Create Date: 2025-10-29 12:41:56.142422

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0e74959c8fd2'
down_revision: Union[str, Sequence[str], None] = 'd40254589bb1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('sql', sa.String(), nullable=True))
    op.add_column('messages', sa.Column('table', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('messages', sa.Column('chart', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('messages', sa.Column('summary', sa.String(), nullable=True))
    op.alter_column('messages', 'chat_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('messages', 'chat_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('messages', 'summary')
    op.drop_column('messages', 'chart')
    op.drop_column('messages', 'table')
    op.drop_column('messages', 'sql')
    # ### end Alembic commands ###
