"""message column changed

Revision ID: 5334852e3b12
Revises: 6688521fcff1
Create Date: 2025-10-26 14:54:37.664475

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5334852e3b12'
down_revision: Union[str, Sequence[str], None] = '6688521fcff1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('chats', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_index(op.f('ix_chats_name'), table_name='chats')
    op.alter_column('connections', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('connections', 'type',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_index(op.f('ix_connections_name'), table_name='connections')
    op.alter_column('csvs', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('csvs', 'file_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('csvs', 'description',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_index(op.f('ix_csvs_description'), table_name='csvs')
    op.drop_index(op.f('ix_csvs_file_name'), table_name='csvs')
    op.drop_index(op.f('ix_csvs_name'), table_name='csvs')
    op.add_column('messages', sa.Column('content', sa.String(), nullable=False))
    op.add_column('messages', sa.Column('type', sa.String(), nullable=False))
    op.drop_index(op.f('ix_messages_text'), table_name='messages')
    op.drop_column('messages', 'text')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('text', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_index(op.f('ix_messages_text'), 'messages', ['text'], unique=False)
    op.drop_column('messages', 'type')
    op.drop_column('messages', 'content')
    op.create_index(op.f('ix_csvs_name'), 'csvs', ['name'], unique=False)
    op.create_index(op.f('ix_csvs_file_name'), 'csvs', ['file_name'], unique=False)
    op.create_index(op.f('ix_csvs_description'), 'csvs', ['description'], unique=False)
    op.alter_column('csvs', 'description',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('csvs', 'file_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('csvs', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.create_index(op.f('ix_connections_name'), 'connections', ['name'], unique=False)
    op.alter_column('connections', 'type',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('connections', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.create_index(op.f('ix_chats_name'), 'chats', ['name'], unique=False)
    op.alter_column('chats', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
