"""csv table added

Revision ID: b398732fe4b1
Revises: 82b70f414eef
Create Date: 2025-10-26 09:18:21.997866

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b398732fe4b1'
down_revision: Union[str, Sequence[str], None] = '82b70f414eef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('csvs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('file_name', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('columns', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_csvs_description'), 'csvs', ['description'], unique=False)
    op.create_index(op.f('ix_csvs_file_name'), 'csvs', ['file_name'], unique=False)
    op.create_index(op.f('ix_csvs_id'), 'csvs', ['id'], unique=False)
    op.create_index(op.f('ix_csvs_name'), 'csvs', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_csvs_name'), table_name='csvs')
    op.drop_index(op.f('ix_csvs_id'), table_name='csvs')
    op.drop_index(op.f('ix_csvs_file_name'), table_name='csvs')
    op.drop_index(op.f('ix_csvs_description'), table_name='csvs')
    op.drop_table('csvs')
    # ### end Alembic commands ###
